spring:
  application:
    name: VirtualShop

  datasource:
    url: jdbc:mysql://localhost:5432/virtualshop
    username: postgres
    password: postgres
    driver-class-name: com.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true
